module:
  _target_: torchgeo.trainers.SemanticSegmentationTask
  model: "unet"
  backbone: "resnet18"
  weights: null
  in_channels: 9
  num_classes: 5
  loss: "ce"
  ignore_index: 0
  learning_rate: 1e-3
  learning_rate_schedule_patience: 6

datamodule:
  _target_: torchgeo.datamodules.L7IrishDataModule
  root: "/projects/dali/data/l7irish"
  batch_size: 64
  patch_size: 224
  num_workers: 10
  crs: epsg:3857
  length: 25000

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu
  devices:
    - 0
  min_epochs: 20
  max_epochs: 100

program:
  seed: 0
  output_dir: "/scratch.local/yichia3/output/l7irish"
  log_dir: "/scratch.local/yichia3/logs/l7irish"
  overwrite: True
  experiment_name: l7irish
