module:
  _target_: torchgeo.trainers.SemanticSegmentationTask
  model: "unet"
  backbone: "resnet18"
  weights: null
  in_channels: 7
  num_classes: 18
  loss: "ce"
  ignore_index: 0
  learning_rate: 1e-3
  learning_rate_schedule_patience: 6

datamodule:
  _target_: torchgeo.datamodules.SSL4EOLBenchmarkDataModule
  root: "/scratch.local/yichia3/ssl4eo_benchmark_landsat"
  sensor: "oli_sr"
  product: "cdl"
  classes: [0, 1, 5, 24, 36, 37, 61, 111, 121, 122, 131, 141, 142, 143, 152, 176, 190, 195]
  batch_size: 64
  num_workers: 10
  download: True

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu
  devices:
    - 0
  min_epochs: 20
  max_epochs: 100

program:
  seed: 0
  output_dir: "/scratch.local/yichia3/output/oli_sr_cdl"
  log_dir: "/scratch.local/yichia3/logs/oli_sr_cdl"
  overwrite: True
  experiment_name: test_downstream_oli_sr_cdl
